version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000

  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=backend.main
      - USE_MOCK_MAGENTA=${USE_MOCK_MAGENTA:-false}
    command: python -m backend.main 